# ==================================
[global]
[global.instruments]
[global.instruments.NI9205_Power1]
type = "ForwardPower"

[global.instruments.NI9205_Power2]
type = "ReflectedPower"

# ==================================
[E1]
position = 0e0

[E1.instruments]
[E1.instruments.NI9205_MP1l]
type = "CurrentProbe"

[E1.instruments.NI9205_E1]
type = "ElectricFieldProbe"

# ==================================
[V1]
position = 0.130

[V1.instruments]
[V1.instruments.NI9205_Penning1]
type = "Penning"

# ==================================
[E2]
position = 0.26

[E2.instruments]
[E2.instruments.NI9205_MP2l]
type = "CurrentProbe"

[E2.instruments.NI9205_E2]
type = "ElectricFieldProbe"

# ==================================
[E3]
position = 0.39

[E3.instruments]
[E3.instruments.NI9205_MP3l]
type = "CurrentProbe"

[E3.instruments.NI9205_E3]
type = "ElectricFieldProbe"

# ==================================
[V2]
position = 0.611

[V2.instruments]
[V2.instruments.NI9205_Penning]
type = "Penning"

# ==================================
[E4]
position = 0.611

[E4.instruments]
[E4.instruments.NI9205_MP4l]
type = "CurrentProbe"

[E4.instruments.NI9205_E4]
type = "ElectricFieldProbe"

# [E8]
# position = 0.611
# 
# [E8.instruments]
# [E8.instruments.NI9205_MP8l]
# type = "CurrentProbe"

# ==================================
# [OF]
# position = 0.656
# 
# [OF.instruments]
# [OF.instruments.NI9205_Arc1]
# type = "OpticalFibre"

# ==================================
[E5]
position = 0.832

[E5.instruments]
[E5.instruments.NI9205_MP5l]
type = "CurrentProbe"

[E5.instruments.NI9205_E5]
type = "ElectricFieldProbe"

# ==================================
[E6]
position = 0.962

[E6.instruments]
[E6.instruments.NI9205_MP6l]
type = "CurrentProbe"

[E6.instruments.NI9205_E6]
type = "ElectricFieldProbe"

# ==================================
[V3]
position = 1.092

[V3.instruments]
[V3.instruments.NI9205_Penning2]
type = "Penning"

# ==================================
[E7]
position = 1.222

[E7.instruments]
[E7.instruments.NI9205_MP7l]
type = "CurrentProbe"

[E7.instruments.NI9205_E7]
type = "ElectricFieldProbe"

